"""Phase 14.2 / L19 — workbook discovery CLI entry.

Usage::

    python -m aa_model.ingestion.discover_workbook \\
        --workbook /path/to/Cashflow\\ Modeling\\ v7.xlsx \\
        --mode privacy_safe \\
        --dry-run

    python -m aa_model.ingestion.discover_workbook \\
        --workbook /path/to/Cashflow\\ Modeling\\ v7.xlsx \\
        --out configs/workbook_v7_manifest_local.yaml \\
        --mode local_private \\
        --workbook-version v7

Privacy posture
===============

* Default mode: ``privacy_safe`` — redacts non-structural sheet
  names; suitable for chat / committed scaffold / public report.
* ``local_private`` — preserves real sheet names; the CLI refuses
  to write the output to anything other than a path ending in
  ``_local.yaml`` or under ``data/external/``. Those paths are
  gitignored per the Phase 14.x conventions.

The CLI never prints cell contents, dollar values, or per-row
classification detail. ``--dry-run`` prints aggregate structural
diagnostics only.
"""

from __future__ import annotations

import argparse
from pathlib import Path

from aa_model.ingestion.discovery import (
    build_draft_manifest,
    discover_workbook,
    render_aggregate_diagnostics,
)

_LOCAL_PRIVATE_PATH_HINTS: tuple[str, ...] = (
    "_local.yaml",
    "data/external/",
    "data\\external\\",
)


def _check_local_private_path(out: Path) -> None:
    """Refuse to write a local_private manifest to a non-gitignored path."""
    s = str(out)
    if not any(hint in s for hint in _LOCAL_PRIVATE_PATH_HINTS):
        raise SystemExit(
            f"refusing to write local_private output to {out!s}: "
            f"path must end in '_local.yaml' or live under data/external/ "
            f"so the localized manifest stays gitignored. Override by "
            f"renaming the output target."
        )


def _emit_yaml(manifest, out: Path) -> None:
    import yaml

    # Pydantic model_dump preserves the schema's field order.
    data = manifest.model_dump(mode="json")
    with out.open("w", encoding="utf-8") as f:
        f.write("# Generated by aa_model.ingestion.discover_workbook.\n")
        f.write("# Review + complete row_classification_rules locally before ingestion.\n")
        f.write("# DO NOT commit this file if it carries live sheet identifiers.\n\n")
        yaml.safe_dump(data, f, sort_keys=False, allow_unicode=True)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="aa_model.ingestion.discover_workbook",
        description=(
            "Phase 14.2 workbook discovery. Reads the workbook read-only, "
            "discovers structural layout, and emits a draft manifest YAML "
            "or aggregate diagnostics."
        ),
    )
    parser.add_argument("--workbook", required=True, help="Path to the .xlsx workbook.")
    parser.add_argument(
        "--mode",
        choices=["privacy_safe", "local_private"],
        default="privacy_safe",
        help=(
            "privacy_safe (default) redacts non-structural sheet names; "
            "local_private preserves real names but refuses to write to "
            "non-gitignored paths."
        ),
    )
    parser.add_argument(
        "--out",
        default=None,
        help=(
            "Output path for the draft manifest YAML. If omitted, prints "
            "the aggregate diagnostics to stdout."
        ),
    )
    parser.add_argument(
        "--workbook-version",
        default="v_unknown",
        help="workbook_version string for the draft manifest.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print aggregate structural diagnostics; do not write any file.",
    )
    args = parser.parse_args(argv)

    workbook = Path(args.workbook)
    discovery = discover_workbook(workbook)
    draft = build_draft_manifest(discovery, mode=args.mode, workbook_version=args.workbook_version)

    diag = render_aggregate_diagnostics(discovery, draft)

    if args.dry_run:
        print(diag)
        return 0

    if args.out is None:
        # No output path → print diagnostics only (no manifest YAML
        # leaks into stdout).
        print(diag)
        print()
        print(
            "(No --out path provided; manifest not emitted. Re-run with "
            "--out PATH to write the draft.)"
        )
        return 0

    out = Path(args.out)
    if args.mode == "local_private":
        _check_local_private_path(out)
    out.parent.mkdir(parents=True, exist_ok=True)
    _emit_yaml(draft.manifest, out)

    print(diag)
    print()
    print(f"draft manifest written: {out}")
    if args.mode == "privacy_safe":
        print(
            "  (privacy_safe mode — sheet names redacted; suitable for "
            "committed scaffold or public review.)"
        )
    else:
        print("  (local_private mode — real sheet names preserved; " "do NOT commit this file.)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
